[2024-01-22T12:16:20.706+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: write_to_redshift.create_redshift_table manual__2024-01-22T10:16:14.971309+00:00 [queued]>
[2024-01-22T12:16:20.711+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: write_to_redshift.create_redshift_table manual__2024-01-22T10:16:14.971309+00:00 [queued]>
[2024-01-22T12:16:20.711+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-22T12:16:20.729+0200] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): create_redshift_table> on 2024-01-22 10:16:14.971309+00:00
[2024-01-22T12:16:20.731+0200] {standard_task_runner.py:60} INFO - Started process 6267 to run task
[2024-01-22T12:16:20.734+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'write_to_redshift', 'create_redshift_table', 'manual__2024-01-22T10:16:14.971309+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/write_to_redshift.py', '--cfg-path', '/tmp/tmpbamihs2o']
[2024-01-22T12:16:20.735+0200] {standard_task_runner.py:88} INFO - Job 218: Subtask create_redshift_table
[2024-01-22T12:16:20.775+0200] {task_command.py:423} INFO - Running <TaskInstance: write_to_redshift.create_redshift_table manual__2024-01-22T10:16:14.971309+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-22T12:16:20.828+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='write_to_redshift' AIRFLOW_CTX_TASK_ID='create_redshift_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-22T10:16:14.971309+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-22T10:16:14.971309+00:00'
[2024-01-22T12:16:20.834+0200] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2024-01-22T12:16:20.836+0200] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 'your_redshift_conn_id', switching to empty.
[2024-01-22T12:16:20.837+0200] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-01-22T12:16:23.119+0200] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mahmoud/airflow/dags/write_to_redshift.py", line 11, in create_table_in_redshift
    redshift_conn = redshift_hook.get_conn()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 197, in get_conn
    conn_params = self._get_conn_params()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 85, in _get_conn_params
    conn.login, conn.password, conn.port = self.get_iam_token(conn)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 137, in get_iam_token
    redshift_client = AwsBaseHook(aws_conn_id=self.aws_conn_id, client_type="redshift").conn
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 704, in conn
    return self.get_client_type(region_name=self.region_name)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 674, in get_client_type
    return session.client(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/client.py", line 613, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2024-01-22T12:16:23.123+0200] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=write_to_redshift, task_id=create_redshift_table, execution_date=20240122T101614, start_date=20240122T101620, end_date=20240122T101623
[2024-01-22T12:16:23.135+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 218 for task create_redshift_table (You must specify a region.; 6267)
[2024-01-22T12:16:23.177+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-22T12:16:23.186+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
