[2024-01-15T18:51:13.985+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_with_python_operator.multiply_1 manual__2024-01-15T16:51:09.830581+00:00 [queued]>
[2024-01-15T18:51:13.990+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_with_python_operator.multiply_1 manual__2024-01-15T16:51:09.830581+00:00 [queued]>
[2024-01-15T18:51:13.990+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-15T18:51:14.011+0200] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): multiply_1> on 2024-01-15 16:51:09.830581+00:00
[2024-01-15T18:51:14.014+0200] {standard_task_runner.py:60} INFO - Started process 39420 to run task
[2024-01-15T18:51:14.017+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'xcom_with_python_operator', 'multiply_1', 'manual__2024-01-15T16:51:09.830581+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/XCom.py', '--cfg-path', '/tmp/tmpoc6fq1tg']
[2024-01-15T18:51:14.018+0200] {standard_task_runner.py:88} INFO - Job 88: Subtask multiply_1
[2024-01-15T18:51:14.055+0200] {task_command.py:423} INFO - Running <TaskInstance: xcom_with_python_operator.multiply_1 manual__2024-01-15T16:51:09.830581+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-15T18:51:14.118+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='xcom_with_python_operator' AIRFLOW_CTX_TASK_ID='multiply_1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-15T16:51:09.830581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-15T16:51:09.830581+00:00'
[2024-01-15T18:51:14.122+0200] {logging_mixin.py:188} INFO - value None
[2024-01-15T18:51:14.122+0200] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mahmoud/airflow/dags/XCom.py", line 15, in multiply_100
    return value*100
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[2024-01-15T18:51:14.125+0200] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=xcom_with_python_operator, task_id=multiply_1, execution_date=20240115T165109, start_date=20240115T165113, end_date=20240115T165114
[2024-01-15T18:51:14.142+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 88 for task multiply_1 (unsupported operand type(s) for *: 'NoneType' and 'int'; 39420)
[2024-01-15T18:51:14.149+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-15T18:51:14.164+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
