[2024-01-18T15:51:41.290+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: write_to_postgresql.create_table scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-18T15:51:41.296+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: write_to_postgresql.create_table scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-18T15:51:41.296+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-18T15:51:41.313+0200] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_table> on 2024-01-17 00:00:00+00:00
[2024-01-18T15:51:41.314+0200] {standard_task_runner.py:60} INFO - Started process 17717 to run task
[2024-01-18T15:51:41.317+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'write_to_postgresql', 'create_table', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/write_to_postgresql.py', '--cfg-path', '/tmp/tmpjba23grv']
[2024-01-18T15:51:41.319+0200] {standard_task_runner.py:88} INFO - Job 210: Subtask create_table
[2024-01-18T15:51:41.353+0200] {task_command.py:423} INFO - Running <TaskInstance: write_to_postgresql.create_table scheduled__2024-01-17T00:00:00+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-18T15:51:41.443+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='write_to_postgresql' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-17T00:00:00+00:00'
[2024-01-18T15:51:41.444+0200] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXIST employees(
            id SERIAL PRIMARY KEY,
            name VARCHAR (255) NOT NULL,
            added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
            
[2024-01-18T15:51:41.463+0200] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres_cnn` isn't defined
[2024-01-18T15:51:41.486+0200] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=write_to_postgresql, task_id=create_table, execution_date=20240117T000000, start_date=20240118T135141, end_date=20240118T135141
[2024-01-18T15:51:41.500+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 210 for task create_table (The conn_id `my_postgres_cnn` isn't defined; 17717)
[2024-01-18T15:51:41.529+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-18T15:51:41.543+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
